export const PALETTE: Record<string, string> = {
    k: '#000000',
    w: '#ffffff',
    g: '#c0c0c0',
    d: '#808080',
    n: '#000080',
    B: '#1060e0',
    t: '#008080',
    y: '#ffd800',
    o: '#8a5a19',
    O: '#c98b3a',
    r: '#d02020',
    G: '#20a040',
};

export const ICONS = {
    computer: [
        '................',
        '.kkkkkkkkkkkkkk.',
        '.kggggggggggggk.',
        '.kgttttttttttgk.',
        '.kgttttttttttgk.',
        '.kgttttttttttgk.',
        '.kgttttttttttgk.',
        '.kgttttttttttgk.',
        '.kggggggggggggk.',
        '.kkkkkkkkkkkkkk.',
        '.....kggggk.....',
        '...kkkkkkkkkk...',
        '...kggggggggk...',
        '...kkkkkkkkkk...',
        '................',
        '................',
    ],
    trash: [
        '................',
        '......kkkk......',
        '..kkkkkkkkkkkk..',
        '..kggggggggggk..',
        '..kkkkkkkkkkkk..',
        '...kgdgdgdgdk...',
        '...kgdgdgdgdk...',
        '...kgdgdgdgdk...',
        '...kgdgdgdgdk...',
        '...kgdgdgdgdk...',
        '...kgdgdgdgdk...',
        '...kgdgdgdgdk...',
        '...kgdgdgdgdk...',
        '...kkkkkkkkkk...',
        '................',
        '................',
    ],
    logo: [
        '................',
        '................',
        '.rrrrrr..GGGGGG.',
        '.rrrrrr..GGGGGG.',
        '.rrrrrr..GGGGGG.',
        '.rrrrrr..GGGGGG.',
        '.rrrrrr..GGGGGG.',
        '.rrrrrr..GGGGGG.',
        '................',
        '.BBBBBB..yyyyyy.',
        '.BBBBBB..yyyyyy.',
        '.BBBBBB..yyyyyy.',
        '.BBBBBB..yyyyyy.',
        '.BBBBBB..yyyyyy.',
        '.BBBBBB..yyyyyy.',
        '................',
    ],
    info: [
        '.....kkkkkk.....',
        '...kkBBBBBBkk...',
        '..kBBBBwwBBBBk..',
        '.kBBBBBwwBBBBBk.',
        '.kBBBBBBBBBBBBk.',
        'kBBBBBwwwBBBBBBk',
        'kBBBBBBwwBBBBBBk',
        'kBBBBBBwwBBBBBBk',
        'kBBBBBBwwBBBBBBk',
        'kBBBBBBwwBBBBBBk',
        '.kBBBBBwwBBBBBk.',
        '.kBBBBwwwwBBBBk.',
        '..kBBBBBBBBBBk..',
        '...kkBBBBBBkk...',
        '.....kkkkkk.....',
        '................',
    ],
    warning: [
        '.......kk.......',
        '......kyyk......',
        '......kyyk......',
        '.....kyyyyk.....',
        '.....kykkyk.....',
        '....kyykkyyk....',
        '....kyykkyyk....',
        '...kyyykkyyyk...',
        '...kyyykkyyyk...',
        '..kyyyykkyyyyk..',
        '..kyyyyyyyyyyk..',
        '.kyyyyykkyyyyyk.',
        '.kyyyyykkyyyyyk.',
        'kyyyyyyyyyyyyyyk',
        'kkkkkkkkkkkkkkkk',
        '................',
    ],
    floppy: [
        '................',
        '.kkkkkkkkkkkkkk.',
        '.knnkggggggknnk.',
        '.knnkgggkkgknnk.',
        '.knnkgggkkgknnk.',
        '.knnkggggggknnk.',
        '.knnnkkkkkknnnk.',
        '.knnnnnnnnnnnnk.',
        '.knnwwwwwwwwnnk.',
        '.knnwkkkkkkwnnk.',
        '.knnwwwwwwwwnnk.',
        '.knnwkkkkkkwnnk.',
        '.knnwwwwwwwwnnk.',
        '.kkkkkkkkkkkkkk.',
        '................',
        '................',
    ],
    program: [
        '................',
        '................',
        '.kkkkkkkkkkkkkk.',
        '.knnnnnnnnnnwnk.',
        '.kkkkkkkkkkkkkk.',
        '.kwwwwwwwwwwwwk.',
        '.kwGGGwwwwwwwwk.',
        '.kwGGGwddddddwk.',
        '.kwGGGwwwwwwwwk.',
        '.kwwwwwddddddwk.',
        '.kwwwwwwwwwwwwk.',
        '.kwddddddddddwk.',
        '.kwwwwwwwwwwwwk.',
        '.kkkkkkkkkkkkkk.',
        '................',
        '................',
    ],
    'control-panel': [
        '................',
        '.kkkkkkkkkkkkkk.',
        '.knnnnnnnnnnnnk.',
        '.kkkkkkkkkkkkkk.',
        '.kggggggggggggk.',
        '.kgddddrrddddgk.',
        '.kggggggggggggk.',
        '.kgddddddyyddgk.',
        '.kggggggggggggk.',
        '.kgddGGddddddgk.',
        '.kggggggggggggk.',
        '.kkkkkkkkkkkkkk.',
        '................',
        '................',
        '................',
        '................',
    ],
    key: [
        '................',
        '................',
        '................',
        '................',
        '..kkkk..........',
        '.kyyyyk.........',
        'kyykkyykkkkkkkk.',
        'kyykkyyyyyyyyyyk',
        '.kyyyykkkkykyykk',
        '..kkkk....kk.kk.',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
    ],
    mail: [
        '................',
        '................',
        '................',
        'kkkkkkkkkkkkkkkk',
        'kwkwwwwwwwwwwkwk',
        'kwwkwwwwwwwwkwwk',
        'kwwwkwwwwwwkwwwk',
        'kwwwwkwwwwkwwwwk',
        'kwwwwwkwwkwwwwwk',
        'kwwwwkwkkwkwwwwk',
        'kwwwkwwwwwwkwwwk',
        'kwwkwwwwwwwwkwwk',
        'kwkwwwwwwwwwwkwk',
        'kkkkkkkkkkkkkkkk',
        '................',
        '................',
    ],
    worknet: [
        '.....kkkkkk.....',
        '...kkBBGGBBkk...',
        '..kBBGGGGBBBBk..',
        '.kBBBGGGGGBBBBk.',
        '.kBBGGGGGBBBGGk.',
        'kBBBBGGGBBBBGGGk',
        'kBBBBBGGBBBBBGGk',
        'kBBBBBBGGBBBBBBk',
        'kBBBBBBGGGGBBBBk',
        'kBGGBBBBGGGGBBBk',
        '.kGGGBBBBGGGBBk.',
        '.kBGGBBBBGGBBBk.',
        '..kBBBBBBGBBBk..',
        '...kkBBBBBBkk...',
        '.....kkkkkk.....',
        '................',
    ],
    clock: [
        '.....kkkkkk.....',
        '...kkwwwwwwkk...',
        '..kwwwwkwwwwwk..',
        '.kwwwwwkwwwwwwk.',
        '.kwwwwwkwwwwwwk.',
        'kwwwwwwkwwwwwwwk',
        'kwwwwwwkwwwwwwwk',
        'kwkwwwwkkkkkwwkk',
        'kwwwwwwwwwwwwwwk',
        'kwwwwwwwwwwwwwwk',
        '.kwwwwwwwwwwwwk.',
        '.kwwwwwwwwwwwwk.',
        '..kwwwwwkwwwwk..',
        '...kkwwwwwwkk...',
        '.....kkkkkk.....',
        '................',
    ],
    'text-file': [
        '................',
        '..kkkkkkkkk.....',
        '..kwwwwwwwkk....',
        '..kwwwwwwwkwk...',
        '..kwkkkkwwkkkk..',
        '..kwwwwwwwwwwk..',
        '..kwkkkkkkkkwk..',
        '..kwwwwwwwwwwk..',
        '..kwkkkkkkkkwk..',
        '..kwwwwwwwwwwk..',
        '..kwkkkkkkwwwk..',
        '..kwwwwwwwwwwk..',
        '..kwkkkkkkkkwk..',
        '..kwwwwwwwwwwk..',
        '..kkkkkkkkkkkk..',
        '................',
    ],
    mine: [
        '................',
        '.......k........',
        '.......k........',
        '...k.kkkkk.k....',
        '....kkkkkkk.....',
        '...kkwwkkkkk....',
        '...kkwwkkkkk....',
        '.kkkkkkkkkkkkk..',
        '...kkkkkkkkk....',
        '...kkkkkkkkk....',
        '....kkkkkkk.....',
        '...k.kkkkk.k....',
        '.......k........',
        '.......k........',
        '................',
        '................',
    ],
    flag: [
        '................',
        '................',
        '................',
        '.......rk.......',
        '.....rrrk.......',
        '...rrrrrk.......',
        '.....rrrk.......',
        '.......rk.......',
        '........k.......',
        '........k.......',
        '......kkkkk.....',
        '....kkkkkkkkk...',
        '................',
        '................',
        '................',
        '................',
    ],
    'face-smile': [
        '.....kkkkkk.....',
        '...kkyyyyyykk...',
        '..kyyyyyyyyyyk..',
        '.kyyyyyyyyyyyyk.',
        '.kyyykyyyykyyyk.',
        'kyyyykyyyykyyyyk',
        'kyyyyyyyyyyyyyyk',
        'kyyyyyyyyyyyyyyk',
        'kyyyyyyyyyyyyyyk',
        'kyyykyyyyyykyyyk',
        '.kyyykyyyykyyyk.',
        '.kyyyykkkkyyyyk.',
        '..kyyyyyyyyyyk..',
        '...kkyyyyyykk...',
        '.....kkkkkk.....',
        '................',
    ],
    'face-dead': [
        '.....kkkkkk.....',
        '...kkyyyyyykk...',
        '..kyyyyyyyyyyk..',
        '.kyykykyykykyyk.',
        '.kyyykyyyykyyyk.',
        'kyyykykyykykyyyk',
        'kyyyyyyyyyyyyyyk',
        'kyyyyyyyyyyyyyyk',
        'kyyyyyyyyyyyyyyk',
        'kyyyyykkkkyyyyyk',
        '.kyyykyyyykyyyk.',
        '.kyyyyyyyyyyyyk.',
        '..kyyyyyyyyyyk..',
        '...kkyyyyyykk...',
        '.....kkkkkk.....',
        '................',
    ],
    'face-cool': [
        '.....kkkkkk.....',
        '...kkyyyyyykk...',
        '..kyyyyyyyyyyk..',
        '.kyyyyyyyyyyyyk.',
        '.kkkkkkkkkkkkkk.',
        'kykkkkykykkkkkyk',
        'kyykkkyyykkkyyyk',
        'kyyyyyyyyyyyyyyk',
        'kyyyyyyyyyyyyyyk',
        'kyyykyyyyyykyyyk',
        '.kyyykyyyykyyyk.',
        '.kyyyykkkkyyyyk.',
        '..kyyyyyyyyyyk..',
        '...kkyyyyyykk...',
        '.....kkkkkk.....',
        '................',
    ],
    records: [
        '................',
        '..kkkkkkkkkkkk..',
        '..kyyyyyyyyyyk..',
        '..kyykkkkkkyyk..',
        '..kyyyyyyyyyyk..',
        '.kkkkkkkkkkkkkk.',
        '.kwwwwwwwwwwwwk.',
        '.kwkkkkkwwwwwwk.',
        '.kwwwwwwwwwwwwk.',
        '.kwkkkkkkkkkwwk.',
        '.kwwwwwwwwwwwwk.',
        '.kwkkkkkkwwwwwk.',
        '.kwwwwwwwwwwwwk.',
        '.kkkkkkkkkkkkkk.',
        '..kddddddddddk..',
        '..kkkkkkkkkkkk..',
    ],
    scheduler: [
        '................',
        '.kkkkkkkkkkkkkk.',
        '.knnnnnnnnnnnnk.',
        '.kkkkkkkkkkkkkk.',
        '.kwwkwwkwwkwwwk.',
        '.kwwkGGkwwkwwwk.',
        '.kkkkkkkkkkkkkk.',
        '.kwwkwwkrrkwwwk.',
        '.kwwkwwkrrkwwwk.',
        '.kkkkkkkkkkkkkk.',
        '.kGGkwwkwwkyyyk.',
        '.kGGkwwkwwkyyyk.',
        '.kkkkkkkkkkkkkk.',
        '................',
        '................',
        '................',
    ],
    calendar: [
        '................',
        '...k......k.....',
        '.kkkkkkkkkkkkkk.',
        '.krrrrrrrrrrrrk.',
        '.krrrrrrrrrrrrk.',
        '.kkkkkkkkkkkkkk.',
        '.kwwwwwwwwwwwwk.',
        '.kwwwwkkkwwwwwk.',
        '.kwwwkwwwkwwwwk.',
        '.kwwwwwwkwwwwwk.',
        '.kwwwwwkwwwwwwk.',
        '.kwwwwkwwwwwwwk.',
        '.kwwwkkkkkwwwwk.',
        '.kwwwwwwwwwwwwk.',
        '.kkkkkkkkkkkkkk.',
        '................',
    ],
    browser: [
        '................',
        '.....kkkkkk.....',
        '...kkttwwttkk...',
        '..ktttwwwwtttk..',
        '.kttGGGwwttttk..',
        '.ktGGGGGtttttk..',
        'ktttGGGttttGGtk.',
        'kttttGGtttGGGtk.',
        'ktttttGttttGttk.',
        'kttttttGGtttttk.',
        '.kttttGGGGtkkk..',
        '.kttttGGGtkwwk..',
        '..ktttttttkwwwk.',
        '...kkttttkkkwwwk',
        '.....kkkkk..kwwk',
        '.............kk.',
    ],
    calculator: [
        '................',
        '...kkkkkkkkkk...',
        '...kddddddddk...',
        '...kdGGGGGGdk...',
        '...kdGkGkGGdk...',
        '...kddddddddk...',
        '...kdwdwdwdrk...',
        '...kddddddddk...',
        '...kdwdwdwdrk...',
        '...kddddddddk...',
        '...kdwdwdwdrk...',
        '...kddddddddk...',
        '...kdwdwdwdyk...',
        '...kddddddddk...',
        '...kkkkkkkkkk...',
        '................',
    ],
    notepad: [
        '................',
        '...kkkkkkkkkk...',
        '...kyyyyyyyykk..',
        '...kyykkkkyykyk.',
        '...kyyyyyyyykkkk',
        '...kyykkkkkkyyyk',
        '...kyyyyyyyyyyyk',
        '...kyykkkkkkkyyk',
        '...kyyyyyyyyyyyk',
        '...kyykkkkkyyyyk',
        '...kyyyyyyyyyyyk',
        '...kyykkkkkkkyyk',
        '...kyyyyyyyyyyyk',
        '...kyyyyyyyyyyyk',
        '...kkkkkkkkkkkkk',
        '................',
    ],
} satisfies Record<string, string[]>;

export type IconName = keyof typeof ICONS;

export const GLYPHS = {
    minimize: [
        '........',
        '........',
        '........',
        '........',
        '........',
        '.kkkkkk.',
        '.kkkkkk.',
    ],
    close: [
        'kk....kk',
        '.kk..kk.',
        '..kkkk..',
        '...kk...',
        '..kkkk..',
        '.kk..kk.',
        'kk....kk',
    ],
} satisfies Record<string, string[]>;

export type GlyphName = keyof typeof GLYPHS;
